### ISSUE TITLE
fix: Exit code 0 on database error

### ISSUE THREAD

**Issue by Woynert** [hawks-atlanta/authentication-go#31]
When the database isn't found the program will throw an error but exit in code `0`. 

```sh
authentication  | 2023/08/30 02:20:29 failed to initialize gorm: failed to connect to `host=postgres-db user=username database=database`: dial error (dial tcp 172.20.0.4:5432: connect: connection refused)
authentication  |
authentication  | 2023/08/30 02:20:29 /src/models/db.go:28
authentication  | [error] failed to initialize database, got error failed to connect to `host=postgres-db user=username database=database`: dial error (dial tcp 172.20.0.4:5432: connect: connection refused)
authentication exited with code 0
```

This causes issues for the [gateway's developer docker-compose script](https://github.com/hawks-atlanta/gateway-java). As the developer has to restart the script each time `authentication-go` fails without returning a valid fail exit code.

**Comment by shoriwe** [comment]
After checking, it only appears to kill the docker-compose when detached is not set. But the daemon is still able to restart the container
