### ISSUE TITLE
feat: Get user UUID from token

### ISSUE THREAD

**Issue by Woynert** [hawks-atlanta/authentication-go#39]
## What

Create and endpoint like: `GET /user/uuid`
Which only requires the authorization header and returns the user's `UUID`.

## Why

Currently the only way to get the user's UUID is through the endpoint `/user/uuid/{username}` which requires previous knowledge about the username. But this information should be extractable from the JWT token alone.

## Use case

When implementing https://github.com/hawks-atlanta/gateway-java/issues/27 the required fields to upload a file [according to the SOAP specification](https://github.com/hawks-atlanta/gateway-java/blob/dev/app/src/main/java/gateway/soap/request/CreateFileReq.java) are:

```
  String token;
  String fileName;
  byte[] fileContent;
  UUID location;
```

If we consume the current `/user/uuid/{username}` method. It should be changed to:

```
  String token;
  String username; <- NEW
  String fileName;
  byte[] fileContent;
  UUID location;
```

Which is not ideal since a user could put any name they want.

**Comment by shoriwe** [comment]
Parse the created JWT, the UUID is located in the payload section

Here is an token:

```
eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc3MzM4MTEsInV1aWQiOiI0Mzg2N2Y0ZS00ZDFlLTRlMDMtODM5Zi00YjI5ODMzMTMxNjMifQ.B8ALiQrOGOKYnKlmC2onWbAnd2SK2L0-Nd5eyFLr9glgIPj12ulgB-sgwn7G925li5VeEcXfMIEV1V2pzwFN2A
```

Use this [page](https://jwt.io/)
