### ISSUE TITLE
question: Challenge endpoint

### ISSUE THREAD

**Issue by PedroChaparro** [hawks-atlanta/authentication-go#47]
According to the [spec](https://github.com/hawks-atlanta/authentication-go/blob/main/docs/spec.openapi.yaml), the `/challenge` endpoint is supposed to "verify if the received token is still valid", but it is returning a new token for each request, **even if the given token has not yet expired (assuming that the tokens have a 1-month TTL).**

Is this intentional?

**Comment by shoriwe** [comment]
I see, we could define a new route `/refresh` an leave `/challenge` to only handle return `200 OK` when token is valid.

**Comment by PedroChaparro** [comment]
> I see, we could define a new route `/refresh` an leave `/challenge` to only handle return `200 OK` when token is valid.

There is no problem, we can keep the endpoint as it is now to don't slow down the development.
